services:
  rabbitmq:
    hostname: "rabbit"
    image: rabbitmq:4.0-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
  pg:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_PASSWORD: abc
    ports:
      - "5432:5432"
