services:
  rabbitmq:
    hostname: "rabbit"
    image: rabbitmq:4.0-management-alpine
    ports:
      - 15672:15672
      - 5672:5672

  pg1:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_PASSWORD: abc
    ports:
      - "5433:5432"
    volumes:
      - ./migrations/init_users.sql:/docker-entrypoint-initdb.d/init.sql

  pg2:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_PASSWORD: abc
    ports:
      - "5434:5432"
    volumes:
      - ./migrations/init_products.sql:/docker-entrypoint-initdb.d/init.sql

  pg3:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_PASSWORD: abc
    ports:
      - "5435:5432"
    volumes:
      - ./migrations/init_orders.sql:/docker-entrypoint-initdb.d/init.sql
